import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";

interface PrivacyPolicyDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export default function PrivacyPolicyDialog({ open, onOpenChange }: PrivacyPolicyDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[80vh]" data-testid="dialog-privacy-policy">
        <DialogHeader>
          <DialogTitle className="text-2xl font-bold">Privacy Policy</DialogTitle>
          <DialogDescription>
            CC and C Solutions Pty Ltd Privacy Statement
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[60vh] pr-4">
          <div className="space-y-6 text-sm">
            <section>
              <h3 className="text-lg font-bold mb-3">1. Introduction</h3>
              <p className="mb-4">
                CC and C Solutions Pty Ltd ("CC and C Solutions", "we", "us", "our") recognises the importance of your privacy and is committed to protecting any personal information we collect about you in accordance with the Australian Privacy Principles (APP) incorporated into the Privacy Act 1988.
              </p>
              <p className="mb-4">
                For the purposes of this privacy statement, the word "you" includes ccandcsolutions.com website visitors, registered users and purchasers of CC and C Solutions products and services.
              </p>
              <p className="mb-4">
                In this privacy statement, "CC and C Solutions" means CC and C Solutions Pty Ltd (ABN 65 096 869 680) and its related bodies corporate.
              </p>
              <p className="mb-4">The purpose of this privacy statement is to inform you about:</p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>What personal information about you is collected by CC and C Solutions</li>
                <li>How the information is used</li>
                <li>With whom the information may be shared</li>
                <li>How you can access and change any personal information CC and C Solutions holds about you</li>
                <li>What security procedures are in place to protect the loss, misuse or alteration of your personal information by CC and C Solutions</li>
                <li>How to contact CC and C Solutions</li>
              </ul>
              <p className="mb-4">This privacy statement applies to any personal information you provide to us:</p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>When visiting the CC and C Solutions website</li>
                <li>When using CC and C Solutions online services</li>
                <li>When entering into an agreement with CC and C Solutions</li>
                <li>When you correspond, or communicate with CC and C Solutions over the telephone or in any other manner including by letter, facsimile or email</li>
              </ul>
              <p className="mb-4">
                Failure by you to provide personal information when requested by CC and C Solutions may mean that we are unable to provide certain services and products to you.
              </p>
              <p className="mb-4">
                This privacy policy acknowledges and abides by Australian Privacy Amendment (Enhancing Privacy Protection) Act 2012, which amends the Privacy Act 1988.
              </p>

              <h4 className="font-bold mt-6 mb-3">1.1 What types of information do we collect:</h4>
              <p className="mb-4">CC and C Solutions gathers two types of information about you, namely:</p>
              <p className="mb-2">a. Aggregated information generated by our systems (or third party systems) to track our website traffic but that which does not identify you personally; and</p>
              <p className="mb-4">b. Personal information about you such as your name, address, telephone and facsimile number, email address and in some cases, your billing details.</p>
              <p className="mb-4">
                The type of information that CC and C Solutions collects about you is dependent on how you use the services offered on our website and the products and services you are interested in purchasing from CC and C Solutions.
              </p>
              <p className="mb-4">
                Generally, CC and C Solutions does not collect 'sensitive information' about you. Sensitive information includes (but is not limited to) information about your race or ethnic origin, your religion and your sexual preferences. CC and C Solutions will only collect sensitive information about you in the event that it is necessary for the purpose of providing you with a product or service. In such circumstances, CC and C Solutions will only collect sensitive information with your consent unless we are required by law to collect such information from you.
              </p>

              <h4 className="font-bold mt-6 mb-3">1.2 Collection of aggregate data</h4>
              <p className="mb-4">
                CC and C Solutions collects information on our site visitors collectively, including which sections of the site are most frequently visited, how often and for how long. This data is always used as aggregated, non-personal information. We utilise this information to improve and enhance our services by monitoring the areas on the site which are most popular to you.
              </p>
              <p className="mb-4">
                On information collection, CC and C Solutions comply by the Australian Privacy Principles 1 "open and transparent management of personal information", and Australian Privacy Principles 3, "collection of solicited personal information".
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold mb-3">2. How we collect information</h3>
              <p className="mb-4">
                CC and C Solutions may collect personal information about you when you visit our website and you elect to use our on-line services, when you submit a course enquiry or course booking, when you enter into a contract with CC and C Solutions and, when you deal with CC and C Solutions over the telephone or correspond with CC and C Solutions via facsimile, letter or email or any other mode of communication.
              </p>
              <p className="mb-4">
                Our website may contain links to other websites. CC and C Solutions may also collect personal information about you from our third-party service providers.
              </p>
              <p className="mb-4">
                On how CC and C solutions collect information, CC and C Solutions comply by the Australian Privacy Principles 3, "collection of solicited personal information" and Australian Privacy Principle 5 "notification of the collection of personal information".
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold mb-3">3. How we use your personal information</h3>
              <p className="mb-4">
                Your personal information will be used for two primary purposes. First, it will be used to ensure the proper functioning of CC and C Solutions products and services to provide the highest level of service for our customers. Secondly, your personal information may be used by CC and C Solutions for marketing, planning, product development, research, account administration and fraud and crime prevention and investigation.
              </p>
              <p className="mb-4">CC and C Solutions may use your personal information for one or more of the following purposes or related purposes:</p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>to communicate with you, including via email newsletters</li>
                <li>to facilitate and process contracts between yourself and CC and C Solutions and/or third parties</li>
                <li>to verify your identity</li>
                <li>to identify the number of people using CC and C Solutions website services and establish the nature of their interests</li>
                <li>to respond to enquiries or feedback</li>
                <li>to research and develop existing and new products and services</li>
                <li>to facilitate CC and C Solutions registration</li>
                <li>to ensure the proper functioning of CC and C Solutions services and products</li>
                <li>to conduct CC and C Solutions marketing activities</li>
                <li>to provide you with information about CC and C Solutions and its services and products</li>
                <li>where the personal information is to be used by CC and C Solutions for the purposes described in section 5 of this privacy statement</li>
                <li>when CC and C Solutions is required or authorised by law to disclose the personal information</li>
                <li>when the individual to which the personal information relates specifically consents in writing to the use or disclosure.</li>
              </ul>
              <p className="mb-4">
                From time-to-time CC and C Solutions may send e-newsletters and special offers to users who have registered on the website to receive such information and offers. Users who no longer wish to receive this information can unsubscribe from the service by writing to CC and C Solutions, by sending an email to info@ccandcsolutions.com
              </p>
              <p className="mb-4">
                CC and C Solutions complies by Australia Privacy principle 6 "use or disclosure of personal information".
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold mb-3">4. Disclosure of personal information to third parties</h3>
              <p className="mb-4">
                CC and C Solutions may disclose your personal information to third party contractors who perform services for us including the management and maintenance of our information systems.
              </p>
              <p className="mb-4">
                CC and C Solutions may transfer information to persons outside Australia (e.g. a contractor located in the USA who provides us with services). By giving us your personal information, you consent to such disclosures. In addition, we believe that the recipients of such information are subject to a law, binding scheme or contract which effectively upholds principles for fair handling of the information that are substantially similar to the Australian Privacy Policy.
              </p>
              <p className="mb-4">
                CC and C Solutions may also disclose your personal information internally for the purposes of marketing, planning, product development, research, account administration and other related purposes and externally for the purposes of fraud and crime prevention and investigation and other related purposes. To perform these activities, CC and C Solutions may share your personal information with:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-2">
                <li>service providers such as data processing and data analysis agents, printing contractors, customer service organisations, call centres, professional advisors, auditors, delivery companies and mailing organisations</li>
                <li>other organisations as required or authorised by law, for example, to government or regulatory bodies for the prevention or detection of unlawful activities</li>
              </ul>
              <p className="mb-4">
                Where your personal information is passed on to third party contractors, CC and C Solutions takes reasonable steps to ensure that these individuals and/or organisations are bound by confidentiality and privacy obligations in relation to the protection of your personal information.
              </p>
              <p className="mb-4">
                CC and C Solutions will not share in part or in full any of the information collected for its operational purpose to any of the direct marketing purposes.
              </p>
              <p className="mb-4">
                Other than as outlined above, CC and C Solutions will not disclose your personal information without your consent unless disclosure is necessary to prevent a threat to life or health, authorised or required by law, reasonably necessary to enforce the law or necessary to investigate a suspected unlawful activity.
              </p>
              <p className="mb-4">
                CC and C Solutions complies by Australia Privacy principle 6 – "use or disclosure of personal information" and Australian Privacy Policy 7 – "direct marketing".
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold mb-3">5. Keeping information up to date</h3>
              <p className="mb-4">
                CC and C Solutions strives to ensure that the information we hold about you is accurate, complete and up-to-date at all times.
              </p>
              <p className="mb-4">
                If the personal information we hold about you is inaccurate, incomplete, or no longer up-to-date, or you wish for your details to be removed, please contact CC and C Solutions at info@ccandcsolutions.com so that we may take reasonable steps to address this and/or discuss alternative options with you.
              </p>
              <p className="mb-4">
                CC and C Solutions complies by Australia Privacy principle 13 – "correction of personal information".
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold mb-3">6. Storage and security of your personal information</h3>
              <p className="mb-4">
                CC and C Solutions takes reasonable steps to protect the security of your personal information in accordance with this Australian privacy Policy.
              </p>
              <p className="mb-4">
                While CC and C Solutions strives to protect such information, we cannot ensure or warrant to you that the security of any information you transmit to us or obtain from our online products or services. Accordingly, use is at your own risk.
              </p>
              <p className="mb-4">
                Once any personal information comes into our possession, we will take reasonable steps to protect that information from misuse and loss and from unauthorised access, modification or disclosure.
              </p>
              <p className="mb-4">
                CC and C Solutions complies by Australia Privacy principle 11 – "Security of personal information".
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold mb-3">7. Links to other websites</h3>
              <p className="mb-4">
                The CC and C Solutions website contains links to other websites. Please note that these links are intended for your convenience only.
              </p>
              <p className="mb-4">
                Links to third party websites do not constitute endorsement, sponsorship or approval by CC and C Solutions of the content, policies or practices of those third-party websites.
              </p>
              <p className="mb-4">
                If you have any concerns regarding your privacy when visiting a linked third party, you should ensure that you check the privacy statement/policies of those websites.
              </p>
              <p className="mb-4">
                CC and C Solutions complies by Australia Privacy principle 6 – "use or disclosure of personal information"
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold mb-3">8. Destruction of your personal information</h3>
              <p className="mb-4">
                CC and C Solutions will take reasonable steps to destroy or de-identify any personal information about you once the information is no longer required for the purposes for which it was collected or as authorised or required by law.
              </p>
              <p className="mb-4">
                CC and C Solutions complies by Australia Privacy principle 11 – "Security of personal information".
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold mb-3">9. Privacy regulatory action policy</h3>
              <p className="mb-4">
                CC and C Solutions is fully committed and conform to the Privacy Regulatory Action Policy set out in the Privacy Act 1988 confers on the Commissioner a range of privacy regulatory powers. These include powers that allow the Office of the Australian Information Commissioner (OAIC) to work with entities to facilitate legal compliance and best privacy practice, as well as investigative and enforcement powers to use in cases where a privacy breach has occurred.
              </p>
            </section>

            <section>
              <h3 className="text-lg font-bold mb-3">10. Changes to CC and C Solutions privacy statement</h3>
              <p className="mb-4">
                From time to time, CC and C Solutions may make changes to this privacy statement to reflect how we operate our business and to conform the latest Australian Privacy Policy inclusions and deletions. Accordingly, we encourage you to periodically review this statement to remain informed about how we collect and protect your personal information.
              </p>
              <p className="mb-4">
                Your continued use of the CC and C Solutions website and another business transactions constitutes your acceptance of the collection, use and disclosure of your personal information to the extent outlined in this privacy statement as amended from time to time.
              </p>
              <p className="mb-4">
                For further information about the protection of your privacy, please visit the Australian Federal Privacy Commissioner's website at www.privacy.gov.au.
              </p>
            </section>

            <section className="border-t pt-6 mt-6">
              <h3 className="text-lg font-bold mb-3">Contact Information</h3>
              <p className="mb-2"><strong>Email:</strong> info@ccandcsolutions.com</p>
              <p className="mb-2"><strong>Telephone:</strong> +61 2 9410 9855</p>
              <p className="mb-2"><strong>Facsimile:</strong> +61 2 9487 4227</p>
              <p className="mb-2"><strong>Post:</strong> CC and C Solutions Pty Ltd</p>
              <p>L20 Zenith Tower A, 821 Pacific Highway, Australia</p>
            </section>
          </div>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
